### ISSUE TITLE
Consider detecting (known) setters

### ISSUE THREAD

**Issue by danielnixon** [RebeccaStevens/is-immutable-type#41]
# Suggestion
Amazing lib, thanks for all your work.

Consider this example using `Date`:

```typescript
// This type is evaluated to `ReadonlyDeep`, but...
export type ActuallyMutable = {
  readonly date: Date;
};

// ... we can mutate it via setters on Date.
const foo: ActuallyMutable = {
  date: new Date(),
};

// eslint-disable-next-line functional/no-expression-statements
foo.date.setFullYear(2024);
```

There are a few cases like this beyond just dates, some of which I've considered in https://github.com/agiledigital/readonly-types.

I'm not suggesting any sort of heuristic on methods whose name starts with `set`, but in the case of these well-known types that are built into the JS platform, it may be worth special-casing them and not allowing them to masquerade as `ReadonlyDeep`.

**Comment by RebeccaStevens** [comment]
Yeah, there are types that there is no way to tell that they are mutable via their type data alone. This is the main reason for the `overrides` option.

Currently only `Map` and `Set` are overridden by default. https://github.com/RebeccaStevens/is-immutable-type/blob/main/src/calculate.ts#L45-L50

`Data` and those other types you linked should be added to this list.
