### ISSUE TITLE
False positive on immutable-js Maps

### ISSUE THREAD

**Issue by danielnixon** [RebeccaStevens/is-immutable-type#47]
# Bug Report

This triggers a lint error:

```typescript
import { Map } from "immutable";

// Only readonly types allowed. eslint(functional/prefer-readonly-type)
export const bar: Readonly<Map<string, string>> = Map([["key", "value"]]);
```

But this does not:

```typescript
import { Map as ImmutableJsMap } from "immutable";

export const baz: Readonly<ImmutableJsMap<string, string>> = ImmutableJsMap([
  ["key", "value"],
]);
```

## Expected behavior

Renaming the immutable-js import makes no difference to lint outcome.

## Actual behavior

Renaming the immutable-js import makes a difference to lint outcome.

## Steps to reproduce

See above examples.

## Proposed changes

If possible (and I'm not sure it is, but raising this just in case), detect the built-in `Map` type using more than just its name. We should be able to tell it apart from other (maybe unproblematic or less problematic) types that just happen to share its name.

**Comment by RebeccaStevens** [comment]
I'll need to do some investigation into how this could be done.

**Comment by danielnixon** [comment]
I can think of two possible approaches:

1. Look at the type -> symbol -> declaration -> `getSourceFile` -> `fileName`. If the `Map` came from a file named `lib.dom.d.ts` or similar, it's probably the mutable kind.
2. Look at the other methods on the type. If it includes a telltale `set` method, it's probably the mutable kind.

Both of those have downsides. The main one being neither of them are compatible with the way overrides are specified presently (by type name).

**Comment by danielnixon** [comment]
A refinement to the first idea:

Instead of checking `fileName`, check one or both of these:

```
        isDeclarationFile: boolean;
        /**
         * lib.d.ts should have a reference comment like
         *
         *  /// <reference no-default-lib="true"/>
         *
         * If any other file has this comment, it signals not to include lib.d.ts
         * because this containing file is intended to act as a default library.
         */
        hasNoDefaultLib: boolean;
```

lib.dom.d.ts meets both of those criteria.

A downside to that idea: it wouldn't work for something like `URL` from `@types/node/url.d.ts`.

So maybe the override mechanism should let us specify:

1. the filename of the file that defines the type (if omitted, would match type name following current rules)
2. whether the type is a "built in type", which could vaguely translate to "match any `lib.*.d.ts`"
3. a definitely typed package name to match against, which would then match any source file in the `node_modules/@types/<package_name>`

**Comment by danielnixon** [comment]
You could even consult `ESLintUtils.getParserServices(context).program.getCompilerOptions().typeRoots` to get the directory to match against instead of assuming `node_modules/@types/`: https://www.typescriptlang.org/tsconfig#typeRoots

**Comment by RebeccaStevens** [comment]
We'll probably want to do the same sort of thing that https://github.com/typescript-eslint/typescript-eslint/pull/4436 is doing.

**Comment by danielnixon** [comment]
Oh wow, yeah:

> Each item must be one of:
>
>- A type defined in a file (`{from: "file", name: "Foo", path: "src/foo-file.ts"}` with `path` being an optional path relative >to the project root directory)
>- A type from the default library (`{from: "lib", name: "Foo"}`)
>- A type from a package (`{from: "package", name: "Foo", package: "foo-lib"}`, this also works for types defined in a >typings package).
>
>Additionally, a type may be defined just as a simple string, which then matches the type independently of its origin.

**Comment by RebeccaStevens** [comment]
I think I'll mark this as blocked for now as we'll want to use those new features in `@typescript-eslint/type-utils` v6.

**Comment by RebeccaStevens** [comment]
https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta/
