### ISSUE TITLE
Crash with recursive types

### ISSUE THREAD

**Issue by danielnixon** [RebeccaStevens/is-immutable-type#86]
# Bug Report

```ts
export type Foo = ReadonlyArray<Foo>;
export const foo: Foo = [[]];
```

tsc will happily compile that but `functional/type-declaration-immutability` chokes on it.

Compare to

```ts
export const foo = [[]];
```

which does lint without crashing.

## Expected behavior

Linting completes one way or another

## Actual behavior

```
Oops! Something went wrong! :(

ESLint: 8.35.0

RangeError: Maximum call stack size exceeded
Occurred while linting <snip>.test.ts:1065
Rule: "functional/type-declaration-immutability"
<snip>
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to reproduce

See example above

## Proposed changes

During analysis, keep track of the types you've seen so far and terminate recursion when you see something you've already seen.

**Comment by danielnixon** [comment]
This is something I've dealt with in my own adventures: https://github.com/danielnixon/eslint-plugin-total-functions/blob/master/src/rules/no-unsafe-readonly-mutable-assignment.test.ts#L255-L266

**Comment by danielnixon** [comment]
I never did solve this even more subtle variation though: https://github.com/danielnixon/eslint-plugin-total-functions/issues/192

**Comment by RebeccaStevens** [comment]
I can't seem to recreate this issue.
This library should support recursive types, we have tests for them here: https://github.com/RebeccaStevens/is-immutable-type/blob/main/tests/recursive.test.ts

Would you be able to provide a test case that fails?

**Comment by danielnixon** [comment]
Huh, that is strange. Maybe the issue is in the eslint plugin.

This is very lazy of me (sorry) but you can reproduce via:

```
git clone https://github.com/danielnixon/eslint-plugin-total-functions.git
cd eslint-plugin-total-functions
git checkout "demonstate-stack-overflow"
yarn install
yarn run eslint ./src/stack-overflow.ts
```

The file being linted is one I added to that branch for the purpose of demonstrating. It contains:

```
export type Foo = ReadonlyArray<Foo>;
export const foo: Foo = [[]];
```

`package.json` contains:

```
"eslint": "8.35.0",
"eslint-plugin-functional": "5.0.5",
```

**Comment by RebeccaStevens** [comment]
I can reproduce the error with that. I'll look into why it's happening.

**Comment by RebeccaStevens** [comment]
Looks like there were cases where recursive types weren't being handled correctly.
